<a href="https://colab.research.google.com/github/vaishnavipatil29/Career-Guidance-ML-Project/blob/master/Evaluation_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
url = "https://raw.githubusercontent.com/vaishnavipatil29/Career-Guidance-ML-Project/master/career_pred.csv"
df1 = pd.read_csv(url)
# Dataset is now stored in a Pandas Dataframe

In [4]:
df1.head()

   Acedamic percentage in Operating Systems  ...              Suggested Job Role
0                                        69  ...              Database Developer
1                                        78  ...            Portal Administrator
2                                        71  ...            Portal Administrator
3                                        76  ...  Systems Security Administrator
4                                        92  ...        Business Systems Analyst

[5 rows x 39 columns]

In [5]:
#Data Preprocessing
#1. Handling Missing values:
df1.isna()

       Acedamic percentage in Operating Systems  ...  Suggested Job Role
0                                         False  ...               False
1                                         False  ...               False
2                                         False  ...               False
3                                         False  ...               False
4                                         False  ...               False
...                                         ...  ...                 ...
19995                                     False  ...               False
19996                                     False  ...               False
19997                                     False  ...               False
19998                                     False  ...               False
19999                                     False  ...               False

[20000 rows x 39 columns]

In [9]:
df1=df1.dropna()
df1.isna().sum().sum()

0

In [10]:
df1.duplicated()
df1.drop_duplicates()

       Acedamic percentage in Operating Systems  ...                         Suggested Job Role
0                                            69  ...                         Database Developer
1                                            78  ...                       Portal Administrator
2                                            71  ...                       Portal Administrator
3                                            76  ...             Systems Security Administrator
4                                            92  ...                   Business Systems Analyst
...                                         ...  ...                                        ...
19995                                        83  ...                         Technical Engineer
19996                                        80  ...                         E-Commerce Analyst
19997                                        83  ...              Business Intelligence Analyst
19998                                        68  ...  Software Quality Assurance (QA) / Testing
19999                                        73  ...                     Applications Developer

[20000 rows x 39 columns]

In [11]:
df1.dtypes

Acedamic percentage in Operating Systems     int64
percentage in Algorithms                     int64
Percentage in Programming Concepts           int64
Percentage in Software Engineering           int64
Percentage in Computer Networks              int64
Percentage in Electronics Subjects           int64
Percentage in Computer Architecture          int64
Percentage in Mathematics                    int64
Percentage in Communication skills           int64
Hours working per day                        int64
Logical quotient rating                      int64
hackathons                                   int64
coding skills rating                         int64
public speaking points                       int64
can work long time before system?           object
self-learning capability?                   object
Extra-courses did                           object
certifications                              object
workshops                                   object
talenttests taken?                          object
olympiads                                   object
reading and writing skills                  object
memory capability score                     object
Interested subjects                         object
interested career area                      object
Job/Higher Studies?                         object
Type of company want to settle in?          object
Taken inputs from seniors or elders         object
interested in games                         object
Interested Type of Books                    object
Salary Range Expected                       object
In a Realtionship?                          object
Gentle or Tuff behaviour?                   object
Management or Technical                     object
Salary/work                                 object
hard/smart worker                           object
worked in teams ever?                       object
Introvert                                   object
Suggested Job Role                          object
dtype: object

In [12]:
df1['can work long time before system?']

0        yes
1        yes
2        yes
3         no
4         no
        ...
19995    yes
19996    yes
19997    yes
19998     no
19999    yes
Name: can work long time before system?, Length: 20000, dtype: object

In [13]:
df1['can work long time before system?']=df1['can work long time before system?'].astype('category')
df1['can work long time before system?']=df1['can work long time before system?'].cat.codes
df1['can work long time before system?']

0        1
1        1
2        1
3        0
4        0
        ..
19995    1
19996    1
19997    1
19998    0
19999    1
Name: can work long time before system?, Length: 20000, dtype: int8

In [21]:
for col in df1.select_dtypes(include=['object']).columns:
    df1[col] = df1[col].astype('category')
    df1[col] = df1[col].cat.codes
df1.dtypes

Acedamic percentage in Operating Systems    int64
percentage in Algorithms                    int64
Percentage in Programming Concepts          int64
Percentage in Software Engineering          int64
Percentage in Computer Networks             int64
Percentage in Electronics Subjects          int64
Percentage in Computer Architecture         int64
Percentage in Mathematics                   int64
Percentage in Communication skills          int64
Hours working per day                       int64
Logical quotient rating                     int64
hackathons                                  int64
coding skills rating                        int64
public speaking points                      int64
can work long time before system?            int8
self-learning capability?                    int8
Extra-courses did                            int8
certifications                               int8
workshops                                    int8
talenttests taken?                           int8
olympiads                                    int8
reading and writing skills                   int8
memory capability score                      int8
Interested subjects                          int8
interested career area                       int8
Job/Higher Studies?                          int8
Type of company want to settle in?           int8
Taken inputs from seniors or elders          int8
interested in games                          int8
Interested Type of Books                     int8
Salary Range Expected                        int8
In a Realtionship?                           int8
Gentle or Tuff behaviour?                    int8
Management or Technical                      int8
Salary/work                                  int8
hard/smart worker                            int8
worked in teams ever?                        int8
Introvert                                    int8
Suggested Job Role                           int8
dtype: object